spring.application.name=CKG

spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4-turbo
spring.ai.openai.chat.options.temperature=0.1

analyzer.target.path=C:/Amit/Projects/PhotoShare-BE-master/src/main/java
