spring.application.name=CKG

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4-turbo
spring.ai.openai.chat.options.temperature=0.1

analyzer.target.path=C:/Amit/Projects/PhotoShare-BE-master/src/main/java
