spring.application.name=CKG
server.port=8081

# Spring AI Config
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4-turbo
spring.ai.openai.chat.options.temperature=0.1

# Analyzer Target (Absolute path to the source folder of the project to analyze)
analyzer.target.path=C:/Amit/Projects/PhotoShare-BE-master/
